<option>No avatar</option>
<option>R Archer Female Melee</option>
<option>R Hero Melee</option>
<option>R Shaman</option>
<option>R Scout</option>
<option>D Blademaster</option>
<option>D Hurricane</option>
<option>D Sky Defend</option>
<option>D Burner</option>
<option>D Clasher</option>
<option>M Fighter Defend</option>
<option>U Blood Bat</option>
<option>U DeathBlade</option>
<option>U Adept</option>
<option>U Adept2</option>
<option>U Necrophage</option>
<option>U Ghost</option>
<option>U WCorpse</option>
<option>U Skeleton</option>
<option>T Whelp</option>
<option>S Soothsayer Magic</option>
<option>O Young Ogre</option>
<option>H Arch Mage Female</option>
<option>H White Mage</option>
<option>H Footpad Female</option>
<option>L Cavalry</option>
<option>L Duelist Die</option>
<option>L Royal Guard</option>
<option>L Fencer</option>
<option>L Javelineer</option>
<option>L Shocktrooper</option>
<option>K Warrior</option>
<option>K Lord</option>
<option>K Gryphon Rider</option>
<option>K Guard</option>
<option>K Footpad</option>
<option>K Berserker</option>
<option>K Dragonguard</option>
<option>W Wose</option>
<option>G Wolf Rider</option>
<option>G Spearman</option>
<option>G Impaler Arrack</option>