<?
$db = mysql_connect($databaseserver, $databaseuser, $databasepass);
mysql_select_db($databasename,$db);
$sql="SELECT * FROM $varstable WHERE vars_id = 1";
$result=mysql_query($sql,$db);
$row = mysql_fetch_array($result);
$color1 = $row["color1"];
$color2 = $row["color2"];
$color3 = $row["color3"];
$color4 = $row["color4"];
$color5 = $row["color5"];
$color6 = $row["color6"];
$color7 = $row["color7"];
$font   = $row["font"];
$fontweight   = $row["fontweight"];
$fontsize   = $row["fontsize"];
$header   = $fontsize + 2;
$numgamespage = $row["numgamespage"];
$numplayerspage = $row["numplayerspage"];
$statsnum = $row["statsnum"];
$standingsnogames = $row["standingsnogames"];
$pctnum = $row["pctnum"];
$hotcoldnum = $row["hotcoldnum"];
$gamesmaxday = $row["gamesmaxday"];
$gamesmaxdayplayer = $row["gamesmaxdayplayer"];
$approve = $row["approve"];
$approvegames = $row["approvegames"];
$system = $row["system"];
$pointswin = $row["pointswin"];
$pointsloss = $row["pointsloss"];
$report = $row["report"];
$leaguename = $row["leaguename"];
$newsitems = $row["newsitems"];
$copyright = $row["copyright"];
?>