Messages deleted! Wait, you will automatically redirect...
Click <a href = 'message.php?action=show_message_box'>here</a> to redirect manualy.
{html_entity->redirect url='message.php?action=show_message_box'}